"""add sentiment and is_abusive to comments

Revision ID: af8d91bde740
Revises: dc9d1c844d9b
Create Date: 2025-07-18 05:11:12.463637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8d91bde740'
down_revision: Union[str, Sequence[str], None] = 'dc9d1c844d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sentiment', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('is_abusive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_abusive')
    op.drop_column('comments', 'sentiment')
    # ### end Alembic commands ###
